### ISSUE TITLE
State of the field: how this software compares to other commonly-used packages

### ISSUE THREAD

**Issue by tsamsonov** [jessecambon/joss-test#5]
Dear @jessecambon 

I am currently reviewing this paper for JOSS (https://github.com/openjournals/joss-reviews/issues/3544). One of the paper checks is to ensure that the authors describe _how this software compares to other commonly-used packages_.

I think this requirement assumes a brief overview of other existing R geocoding packages (not only the raw geocoding APIs). Please add some information on how your package advances their functionality. Or if no alternatives exist, state this clearly.  I think both the Summary and the Statement of Need sections are suitable for that purpose.

All the best, Tim.

**Comment by jessecambon** [comment]
Hi @tsamsonov. We have updated the first paragraph of the statement of need to the following:

> Tidygeocoder was created to remove obstacles that can make geocoding time-consuming and challenging. In contrast to other R packages that offer geocoding capabilities as part of a larger feature set or are built around a single geocoding service [ggmap; googleway; hereR; banR; tmaptools; mapboxapi; censusxy; rgeocodio; opencage], tidygeocoder is focused on providing access to many geocoding services through a standard interface.

Let me know if this meets the need. I will also update the paper in the tidygeocoder repository.

**Comment by tsamsonov** [comment]
@jessecambon Great! That's exactly what is needed. I feel that _standardized_ would be better than _standard_ in that case, because the standard is something widely approved and published, while your own 'standard' is specific for tidygeocoder package. But this is my subjective view, and its reasonability is at your discretion. This issue can be closed now.
